version: '3.8'

services:

  app:
    image: todo-flask-mongodb
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo
    hostname: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
