apiVersion: apps/v1

kind: Deployment

metadata:
  name: todo-flask

spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-flask
  template:
    metadata:
      labels:
        app: todo-flask
    spec:
      containers:
      - name: todo-flask
        image: vchrombie/todo-flask-mongodb:latest
        ports:
        - containerPort: 5000
