apiVersion: apps/v1

kind: Deployment

metadata:
  name: todo-flask

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: todo-flask
  template:
    metadata:
      labels:
        app: todo-flask
    spec:
      containers:
      - name: todo-flask
        image: vchrombie/todo-flask-mongodb:latest
        ports:
        - containerPort: 5000
